### PR TITLE
use generic container

### PR DESCRIPTION
**Pull request by pine3ree**
then in `templates.global.php`

(edited)

``` php
return [
    'dependencies' => [
        'invokables' => [
            // setup factory
            Blast\BaseUrl\BasePathHelper::class => Blast\BaseUrl\BasePathHelper::class,            
        ],        
    ],
    // for zend-view
    'view_helpers => [
        'factories' => [
            Blast\BaseUrl\BasePathViewHelper::class => Blast\BaseUrl\BasePathViewHelperFactory::class,            
        ],        
        'aliases' => [
            'basePath' => Blast\BaseUrl\BasePathViewHelper::class,
        ],
    ],
];
```

this make also easy to register a template function in Plates.

### CODE REVIEW

**Comment by pine3ree** [comment]
We could add setup instruction for Plates, I have a simple PlateExtension  example class + factory to register the basePath template function.

kind regards

**Comment by mtymek** [comment]
This will break compatibility with ServiceManager v2. In order to fix it, you'll have to do something like that:

``` php
if (! method_exists($container, 'configure') && method_exists($container, 'getServiceLocator')) {
    $container = $container->getServiceLocator();
}

return new BasePathViewHelper(
            $container->get(BasePathHelper::class)
);
```

Ugly, but it seems to do the job.

**Comment by pine3ree** [comment]
I have not tried yet with zend-servicemanager v2. 
At first sight moving the factory and the alias under the `view_helpers` key should instruct the plugin manager to configure the service/plugin-instance correctly. The  `view_helpers` key is used only by the zend view helper plugin manager which is itself a service-manager (an AbstractPluginManager) and (at least since zend-servicemanager v 2.7.x) it implementes container-interop iface. If we keep the factory inside the `dependencies` the view helper can be used a a service by the generic zend-expressive container. I use this technique to build a template function for Plates.

kind regards

**Comment by pine3ree** [comment]
@mtymek 
I see the problem now.
`$container->get(BasePathHelper::class)` make the AbstractPluginManager expect the BasePathHelper to extend AbstractPluginHelper.

Maybe this package could be splitted in a master package providing only base-url|path detection and subpackages for zend-expressive-zendviewrendere and zend-expressive-platesrenderer, so that the base package does not depend on zend-view at all.

what do you think about it?

kind regards

**Comment by mtymek** [comment]
I'd like idea of splitting this repo - makes it more difficult to maintain. I saw the same duck typing as I attached in my earlier comments somewhere in ZF repos. I'll look into integrating it and test under SMv2 and SMv3.

**Pull request closed without merging**
