### PR TITLE
Add support for Twig renderer

### LINKED ISSUE #16: Support Zend Twig Renderer
At the moment, it supports by default "only" Zend View, would it be possible to also support [Zend Expressive Twig Renderer](https://github.com/zendframework/zend-expressive-twigrenderer/) through `ConfigProvider.php` ?

Thanks a lot :)

### PR DESCRIPTION
**Pull request by jbelien**
Close https://github.com/mtymek/blast-base-url/issues/16

Definitely need some review :)

### CODE REVIEW

**Comment by jbelien** [comment]
Tests are failing but doesn't seem related to my PR.
Should I fix it ?

**Comment by jbelien** [comment]
Any chance this would be merged ? 😔

**Comment by mtymek** [comment]
Uh, indeed it took a while, sorry :)

**Comment by jbelien** [comment]
Nice, thanks a lot ! 🎉 

I realized that I brought an "error" by using `array()` instead of `[]`. I fixed it in #18 !

**Pull request merged**
